<%= Rails.env %>:
  search:
    - all
    - artist
    - title
    - location
    - discoveryplace
    - genre
    - material
    - keyword
    - description
    - date
    - credits
    - rights_reproduction
    - rights_work
    - record_id
    - record_object_id
    - rating_average
    - rating_count
    - user_comments
  sort:
    - relevance
    - artist
    - title
    - location
    - date
    - credits
    - rights_work
    - rights_reproduction
    - rating_average
    - rating_count
  mappings:
    all:
      - '*'
    artist:
      - artist
      - artist_normalized
      - identity_artist
    title:
      - title^2
      - subtitle
    location:
      - location
      - institution
    discoveryplace:
      - discoveryplace
    genre:
      - genre
    material:
      - material
    keyword:
      - keyword
      - keyword_artigo
    description:
      - description
    date:
      - date
    credits:
      - credits
      - rights_reproduction
    rights_reproduction:
      - rights_reproduction
    rights_work:
      - rights_work
    # Use the raw, unanalyzed string field to find exact matches.
    record_id:
      - record_id.raw
    record_object_id:
      - record_object_id.raw
    # Use the raw, unanalyzed float field to find number matches.
    rating_average:
      - rating_average.raw
    # Integer fields do not need to use raw.
    rating_count:
      - rating_count
    comment_count:
      - comment_count
    user_comments:
      - user_comments
  display:
    # Show the standard fields from the search result list view first
    - artist
    - title
    - location
    - date
    - credits
    - rights_work
    - rights_reproduction
    # Show all other fields in alphabetical order thereafter
    - acquisition
    - acquisition_date
    - addition
    - adopted_from
    - annotation
    - annotation_technical
    - archives
    - artist_information
    - artist_normalized
    - authority_files
    - authority_files_artist
    - based_on
    - beneficiary_of_charter
    - biographical_data
    - caption
    - carrier_medium
    - catalogue
    - century
    - circumference
    - classification
    - collection
    - colour
    - comment
    - commissioning
    - condition
    - constituents
    - containerform
    - context_of_publication
    - corporate_body
    - costumer
    - country
    - creation_context
    - culture
    - date_original
    - date_range
    - department
    - depository
    - depth
    - description
    - description_source
    - detail
    - diameter
    - dimensions
    - discoverycontext
    - discoveryplace
    - discovery_date
    - documentation
    - donor
    - edition
    - editions
    - engraver
    - epoch
    - exhibition
    - external_references
    - footnote
    - format_foto
    - frame
    - function
    - further_context_of_publication
    - genre
    - geographic_coordinates
    - granted_by
    - group_works
    - height
    - height_relief
    - history
    - iconclass
    - iconclass_description
    - iconography
    - image_code
    - image_id
    - image_information
    - identity_artist
    - inscription
    - institution
    - inventory_no
    - isbn
    - issuer_of_charter
    - keyword
    - keyword_artigo
    - keyword_content
    - keyword_general
    - keyword_location
    - keyword_person
    - keyword_main_topic
    - keyword_denotated_connotated_incidents_ontogenetics
    - keyword_collections
    - keyword_persons_beings_objects
    - keyword_composition_proximity_persons_objects
    - keyword_posture
    - keyword_gestics
    - keyword_mimics
    - keyword_gaze
    - keyword_body_movement
    - keyword_emotions
    - labels_collection
    - labels_creator
    - language
    - length
    - library_origin
    - license
    - links
    - literature
    - location_building
    - made_by
    - manufacture_place
    - manufacture_place_city
    - manufacture_place_grave
    - manufacture_place_region
    - maps
    - marks
    - material
    - material_technique
    - measure
    - modification
    - motif
    - negative_identifier
    - notationnote
    - number_of_preserved_seals
    - objecttype
    - origin
    - origin_point
    - original_number_of_seals
    - other_seals
    - owner
    - part_of
    - path
    - pattern
    - person
    - person_of_interest
    - photoagency
    - photographer
    - photographed_location
    - picture_variation
    - pictured_location
    - place
    - place_of_issue
    - plan
    - pool
    - portrayal
    - previous_owner
    - print
    - printdetails
    - printer
    - printingplace
    - production
    - production_place
    - provenance
    - publication
    - publicationplace
    - publisher
    - published_in
    - reception
    - record_id
    - record_identifier
    - record_object_id
    - reference_master
    - related_works
    - restauration
    - restriction
    - scene
    - sealing
    - series
    - sheetsize
    - short_explanation
    - shot
    - shot_composition
    - signature
    - similar_pictures_collection
    - size
    - slide_creator
    - sound
    - source_url
    - state
    - status_record
    - structural_element
    - structural_type
    - style_or_mouvement
    - subject
    - subtitle
    - taxonomy
    - technique
    - text
    - textform
    - title_variants
    - topic
    - tradition
    - venue
    - view
    - watermark
    - weblink_literature
    - weight
    - width
    - work_catalogue
    - year
