<%= Rails.env %>:
  boost:
    - amsterdam_museum: 1.0
    - amsterdam_rijksmuseum: 1.4
    - amtub: 1.5
    - arachne: 0.8
    - archgiessen: 1.0
    - artemis: 1.1
    - artemis_bk: 1.1
    - assisi: 1.2
    - beeskow: 0.9
    - berlin_spsg: 1.2
    - berlin_udk: 1.1
    - berlin_winckelmann: 1.0
    - bern: 1.1
    - bochum_kgi: 1.2
    - bochum_ug: 0.8
    - bpk: 1.6
    - caerlangen: 0.8
    - dadaweb: 1.2
    - darmstadt_tu: 0.9
    - daumier: 1.0
    - ddorf: 0.8
    - ddorf_ka: 1.2
    - desanhalt: 1.2
    - digidia: 1.1
    - digidianeu: 1.0
    - dmr: 1.2
    - dresden: 1.1
    - dresden_hfbk: 1.0
    - eichstaett_ub: 1.1
    - erlangen_drucke: 1.1
    - erlangen_zeichnungen: 1.1
    - ethzuerich: 1.0
    - genf: 1.2
    - giessen_kup: 1.2
    - giessen_lri: 0.9
    - goettingen_arch: 1.0
    - gregorsmesse: 1.1
    - halle_kg: 0.9
    - hamburg: 0.9
    - heidicon_aa: 1.2
    - heidicon_ad: 1.2
    - heidicon_al: 1.1
    - heidicon_ar: 1.1
    - heidicon_bp: 1.5
    - heidicon_fb: 0.2
    - heidicon_fk: 1.1
    - heidicon_gs: 1.1
    - heidicon_ha: 1.0
    - heidicon_ka: 1.1
    - heidicon_kb: 1.1
    - heidicon_kg: 1.1
    - heidicon_pu: 1.1
    - heidicon_sh: 1.1
    - heidicon_si: 1.1
    - heidicon_ua: 1.0
    - heidicon_wa: 1.0
    - heidicon_zo: 1.1
    - imago: 1.0
    - kassel: 1.5
    - kgerlangen: 1.0
    - kiel_digicult: 1.0
    - koeln_rba: 1.2
    - koeln_rba_koer: 1.3
    - leipzig: 1.0
    - lueneburg_oppermann: 1.1
    - mainz: 1.0
    - mainz_kb: 1.3
    - marburg_lba: 1.2
    - mka: 1.3
    - muenster_theologie: 1.2
    - oldenburg_afrika: 0.9
    - paderborn: 1.1
    - passau_dilps: 0.8
    - piranesi: 0.9
    - ppo: 1.0
    - requiem: 1.1
    - robertin: 0.8
    - saarbruecken_ifk: 1.2
    - salzburg: 1.0
    - stabi: 1.2
    - theoleik: 0.8
    - trier: 1.1
    - tuberlin: 1.0
    - uustb: 0.9
    - virtualart: 0.9
    - wbarchiv: 0.9
    - zi_muc: 1.4
