<%= Rails.env %>:
  # https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html
  # Default formats:
  - "strict_date_optional_time"
  - "epoch_millis"
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html
  # Custom formats:
  - "yyyy"
  - "yyy"
  - "yyyy G"
  - "yyy G"
