<%= Rails.env %>:
  warburg: []
  miro:
    artemis: []
    augsburg_kg: []
    bern: []
    berlin_ikb_farbdias: []
    bpk: []
    dadaweb: []
    ddorf: []
    digidia: []
    digidianeu: []
    dresden: []
    dresden_hfbk: []
    eichstaett_ub: []
    ffm_conedakor: []
    genf: []
    giessen_kup: []
    halle_kg: []
    hamburg: []
    heidicon_kg: []
    imago: []
    kgerlangen: []
    leipzig: []
    muenster_theologie: []
    passau_dilps: []
    tuberlin: []
