shared:
  # PBKDF2
  hash_function: sha256
  hash_iterations: 5000
  
  asd_secret: <%= ENV['PM_ASD_SECRET'] %>
  secret_key_base: <%= ENV["PM_PANDORA_COOKIE_SECRET"] %>
  oauth_secret: <%= ENV['PM_OAUTH_SECRET'] %>

  # bounce fetcher
  bf_host: Bounce fetcher host
  bf_user: Bounce fetcher user name
  bf_pass: Bounce fetcher password
