---
:results_per_page:
  - 10
  - 20
  - 40
  - 100

:operators:
  - and
  - or
  - and not

:sortable_fields_for_sources:
  - title
  - name

:groupable_fields_for_sources:
  - kind
  - city
  - keywords
  - open_access
