source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# https://rubygems.org/gems/rails/versions
gem 'bootsnap'
gem 'rails', '~> 7.1.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.5'
# Use the Elasticsearch Ruby gem.
# https://rubygems.org/gems/elasticsearch/versions/
# https://www.rubydoc.info/gems/elasticsearch/
# https://www.rubydoc.info/gems/elasticsearch-api/
gem 'elasticsearch', '~> 7.4'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# REWRITE: we need to move it to vendor since we have to patch it
gem 'ruby-nuggets', path: 'vendor/nuggets'

# we load rack-images as a gem to be able to add asd_secrets to urls and to
# have access to image data directly
gem 'rack-images', path: '../rack-images'

# REWRITE: git pull in
gem 'pbkdf2', git: 'https://github.com/emerose/pbkdf2-ruby'

# gem 'activeresource'
gem 'activerecord-session_store'

gem 'i18n-active_record', :require => 'i18n/backend/active_record'

# REWRITE: not part of rails anymore, some dude gemified it
gem 'country_select'

# REWRITE: included for div_for, we should find another solution
gem 'record_tag_helper', '~> 1.0'

gem 'exifr', '~> 1.3.6'

# REWRITE: for unified configuration of all apps
gem 'dotenv'

# TODO: replace all but faraday in the long run
gem 'faraday'

gem 'httpclient', git: 'https://github.com/Shopify/httpclient'
gem 'rest-client'

# REWRITE: or to_xml isn't available
gem 'activemodel-serializers-xml'

# REWRITE: version used by legacy pandora was 0.4.7, not compatible with rails 5
gem 'oauth'

# REWRITE: for generating powerpoint presentations
gem 'powerpoint'

gem 'exception_notification'

# Cross-Origin Resource Sharing (CORS) for Rack compatible web applications
# https://rubygems.org/gems/rack-cors
gem 'rack-cors', require: 'rack/cors'

gem 'rinku' # auto_link replacement

# Indexing
#
# Encode/decode HTML entities
gem 'htmlentities', '~> 4.3.4'
gem 'nokogiri', '~> 1.15.3'
# https://rubygems.org/gems/historical_dating
gem 'historical_dating', git: 'https://github.com/wendig-ou/historical_dating', branch: 'master'

gem 'yard'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 3.29'
  gem 'mry'
  gem 'rubocop', require: false
  gem 'ruby-prof'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  # gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  # gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'faraday-cookie_jar'
  gem 'minitest-retry'
  gem 'rubyzip'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webmock'
end

group :tasks do
  gem 'maruku'
  gem 'ruby-progressbar'
end
